extension CapitalizeFirstCharOfEachWord on String {
  /// Generated by copilot
  String capitalizeFirstCharOfEachWord() {
    return split(' ')
        .map((word) => word[0].toUpperCase() + word.substring(1))
        .join(' ');
  }
}
